export enum ActionTypes {
    SET_BATTERIES = 'SET_BATTERIES',
    SET_DATE_RANGE = 'SET_DATE_RANGE',
    SET_SELECTED_BATTERY_ID = 'SET_SELECTED_BATTERY_ID',
    SET_SELECTED_BATTERY_IDS = 'SET_SELECTED_BATTERY_IDS',
    SET_SEARCH_CLICKED = 'SET_SEARCH_CLICKED',
    SET_TAGS='SET_TAGS',
    SET_CATEGORY='SET_CATEGORY'
}
