const config: IAppConfig = {
    API_BASE_URL: process.env.REACT_APP_API_BASE_URL || '',
    HOMEPAGE: process.env.REACT_APP_HOMEPAGE || '',
    LOG_IN_URL: '/v1/user/login',
    BATTERY_DATA_URL: '/v1/batteries/metadata',
    BATTERY_SEARCH_URL: '/v1/batteries/search',
    HEALTH_FEEDS_URL: '/v1/feeds/',
    HEALTH_FEEDS_BY_BATTERY_ID_URL: '/v1/feeds/batteries',

    HEALTH_VIEW_DATA_URL: '/v1/views/health',
    HEALTH_VIEW_BMS_SOH_DATA_URL: '/v1/views/health/bms_soh',
    HEALTH_VIEW_BATTERY_DEGRADATION_CAPACITY_DATA_URL: '/v1/views/health/battery_degradation_capacity',
    HEALTH_VIEW_BATTERY_DEGRADATION_CYCLES_DATA_URL: '/v1/views/health/battery_degradation_cycles',
    HEALTH_AVG_AGGREGATIONS_URL: 'v1/views/health/avg-aggregations',
    WARRANTY_VIEW_DATA_URL: '/v1/views/warranty',
    WARRANTY_AVG_AGGREGATIONS_URL: '/v1/views/warranty/avg-aggregations',
    WARRANTY_BMS_SOH_GRAPH_DATA_URL: '/v1/views/warranty/bms-soh',
    WARRANTY_EQUIVALENT_CYCLES_GRAPH_DATA_URL: '/v1/views/warranty/equivalent-cycles-count',

    SAFETY_VIEW_DATA_URL: '/v1/views/safety',
    SAFETY_AVG_AGGREGATIONS_URL: 'v1/views/safety/avg-aggregations',
    SAFETY_INCIDENTS_DATA_URL: 'v1/views/safety/safety-incidents',
    SAFETY_HOURLY_TEMPERATURE_DATA_URL: 'v1/views/safety/hourly-temperature-data',

    BATTERY_AUC_LIST_URL: '/v1/auc/list',
    BATTERY_AUC_DOWNLOAD_URL: '/v1/auc/download',
    BATTERY_AUC_GENERATE_URL: '/v1/auc/generate',
    SIGNAL_DATA_URL: '/v1/signals',
    OPERATIONAL_VIEW_DATA_URL: '/v1/views/operational',
    OPERATIONAL_AVG_AGGREGATIONS_DATA_URL: '/v1/views/operational/avg-aggregations',
    OPERATIONAL_CHARGING_CYCLES_DATA_URL: '/v1/views/operational/charging_cycles_graph_data',
    OPERATIONAL_SOC_RANGE_GRAPH_DATA_URL: '/v1/views/operational/soc_range_graph_data',
    TAG_DATA_URL: '/v1/tags',
    CATEGORY_DATA_URL: '/v1/categories',
    FEEDS_URL: '/v1/feeds/filters',
    SIGNAL_EVENT_DATA_URL: '/v1/signals/data',
    FEED_PLOT_URL: '/v1/feeds/interactive-plots',
    SIGNAL_TREE_DATA_URL: '/v1/signals/tree-plot/data',
    OPERATIONAL_VALUED_SOC_GRAPH_DATA_URL: '/v1/views/operational/valued_soc_graph_data',
    OPERATIONAL_CHARGING_CYCLES_GRAPH_DATA_URL: '/v1/views/operational/charging_cycles_graph_data',
    OPERATIONAL_DISCHARGING_CYCLES_GRAPH_DATA_URL: '/v1/views/operational/discharging_cycles_graph_data',

    RELEASE_NOTES_URL: '/v1/release-notes',
};
export default config;
