interface IAppConfig {
    API_BASE_URL: string;
    LOG_IN_URL: string;
    BATTERY_DATA_URL: string;
    HEALTH_FEEDS_URL: string;
    HEALTH_FEEDS_BY_BATTERY_ID_URL: string;
    HEALTH_VIEW_DATA_URL: string;
    HEALTH_VIEW_BMS_SOH_DATA_URL: string;
    BATTERY_SEARCH_URL: string;
    BATTERY_AUC_LIST_URL: string;
    BATTERY_AUC_DOWNLOAD_URL: string;
    BATTERY_AUC_GENERATE_URL: string;
    SIGNAL_DATA_URL: string;
    OPERATIONAL_VIEW_DATA_URL: string;
    OPERATIONAL_AVG_AGGREGATIONS_DATA_URL: string;
    OPERATIONAL_SOC_RANGE_GRAPH_DATA_URL: String;
    OPERATIONAL_VALUED_SOC_GRAPH_DATA_URL: String;
    OPERATIONAL_CHARGING_CYCLES_GRAPH_DATA_URL: String;
    OPERATIONAL_DISCHARGING_CYCLES_GRAPH_DATA_URL: String;
    TAG_DATA_URL: string;
    CATEGORY_DATA_URL: string;
    FEEDS_URL: string;
    HEALTH_AVG_AGGREGATIONS_URL: string;
    WARRANTY_VIEW_DATA_URL: string;
    WARRANTY_AVG_AGGREGATIONS_URL: string;
    WARRANTY_BMS_SOH_GRAPH_DATA_URL: string;
    WARRANTY_EQUIVALENT_CYCLES_GRAPH_DATA_URL: string;
    SAFETY_VIEW_DATA_URL: string;
    SAFETY_AVG_AGGREGATIONS_URL: string;
    SAFETY_INCIDENTS_DATA_URL: string;
    SAFETY_HOURLY_TEMPERATURE_DATA_URL: string;
    SIGNAL_EVENT_DATA_URL: string;
    FEED_PLOT_URL: string;
    HEALTH_VIEW_BATTERY_DEGRADATION_CAPACITY_DATA_URL: string;
    HEALTH_VIEW_BATTERY_DEGRADATION_CYCLES_DATA_URL: string;
    HOMEPAGE: string;
    SIGNAL_TREE_DATA_URL: string;
    OPERATIONAL_CHARGING_CYCLES_DATA_URL: string;
    RELEASE_NOTES_URL: string;
}

interface IErrorResponse {
    detail: string;
}
